version: "3"

services:
  django:
    build: .
    ports:
      - "8000:8000"
    environment:
      ENV: "dev"
      DJANGO_SECRET_KEY: "cxgu#z=quk34u@f0x2*2s9@en&33tn)uf8eg2^_-m6ixurlts@"
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1"
      DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost:8000 127.0.0.1:8000"
      AWS_ACCESS_KEY_ID: "DO00T6EUEF3HNMTEZBM4"
      AWS_SECRET_ACCESS_KEY: "GzubjW0bRKiLsn7UK0EZSYBNlUGe/IN9niu6hdBr82M"
      AWS_STORAGE_BUCKET_NAME: "gmi-backend"
      AWS_S3_ENDPOINT: "give-me-insights.fra1.digitaloceanspaces.com"
    command:
      - sh
      - -c
      - |
        poetry run python manage.py collectstatic --noinput
        poetry run python manage.py migrate
        gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/app
