# Generated by Django 4.1.4 on 2022-12-10 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_alter_datasource_key_alter_datasource_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=6, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('is_expected', models.BooleanField(default=False, help_text='Info whether Event was expected or not (Corona 2019 would have been an unexpected event.)')),
                ('duration', models.IntegerField(default=0)),
                ('duration_unit', models.CharField(choices=[('h', 'hours'), ('d', 'days'), ('y', 'years')], max_length=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project')),
            ],
            options={
                'abstract': False,
                'unique_together': {('key', 'project')},
            },
        ),
    ]
