# Generated by Django 4.1.4 on 2022-12-11 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_alter_event_is_expected_alter_projectlink_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='key',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='key',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='key',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.CreateModel(
            name='SourceDataRowRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('type', models.CharField(choices=[('r', 'Raw'), ('g1', 'Group by one Key'), ('g2', 'Group by two Keys')], db_index=True, max_length=2)),
                ('value', models.JSONField()),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Projects.datasource')),
            ],
            options={
                'abstract': False,
                'unique_together': {('source', 'timestamp', 'type')},
            },
        ),
    ]
