# Generated by Django 4.1.4 on 2022-12-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_alter_sourcedatarowraw_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcedatarowraw',
            options={'ordering': ('timestamp',)},
        ),
    ]
