# Generated by Django 4.1.4 on 2022-12-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_alter_sourcedatarowraw_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='key',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='key',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(editable=False, max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='key',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
