# Generated by Django 4.1.4 on 2022-12-11 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_alter_datasource_key_alter_event_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupedSourceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('type', models.CharField(choices=[('r', 'Raw'), ('g1', 'Group by one Key'), ('g2', 'Group by two Keys')], db_index=True, max_length=2)),
                ('by_key', models.CharField(max_length=12)),
                ('method', models.CharField(choices=[('count', 'Count'), ('mean', 'Mean'), ('sum', 'Sum')], max_length=6)),
                ('values', models.JSONField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.datasource')),
            ],
            options={
                'ordering': ('timestamp',),
                'unique_together': {('source', 'timestamp', 'type', 'by_key', 'method')},
            },
        ),
    ]
