# Generated by Django 4.1.4 on 2022-12-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_groupedsourcedata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupedsourcedata',
            unique_together=set(),
        ),
    ]
