# Generated by Django 4.1.4 on 2022-12-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0012_aggregationcontrol'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupedsourcedata',
            unique_together={('source', 'timestamp', 'type', 'by_key', 'method')},
        ),
    ]
