# Generated by Django 4.1.4 on 2022-12-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0013_alter_groupedsourcedata_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregationcontrol',
            name='is_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aggregationcontrol',
            name='last_health_state',
            field=models.CharField(choices=[('h', 'Healthy'), ('u', 'Unhealthy')], default='h', max_length=1),
        ),
    ]
